import { toast } from "@/components/ui/use-toast";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from "@/views/Fotter/index";
import Navbar from "@/views/Header";
import React from "react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tail Grids',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <div>
      <Navbar />
      {children}
      <Toaster/>
      <Footer />
    </div>        
        </body>
    </html>
  )
}
